CREATE PROCEDURE PRAGEGROUPUPDATE
(	
	 @AGEGROUPID			INT
	,@NAME					VARCHAR(100)
	,@AGEFROM				INT
	,@AGETO					INT
	,@USERCODE				INT
)
AS
BEGIN
	UPDATE TBLAGEGROUP
	SET 
		 FLDNAME			= @NAME
		,FLDAGEFROM			= @AGEFROM
		,FLDAGETO			= @AGETO
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDAGEGROUPID		= @AGEGROUPID
END