CREATE PROCEDURE PRAGEGROUPLIST
(	
	@AGEGROUPID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		 FLDAGEGROUPID
		,FLDNAME
		,FLDAGEFROM
		,FLDAGETO
	FROM TBLAGEGROUP
	WHERE (@AGEGROUPID IS NULL OR FLDAGEGROUPID = @AGEGROUPID)
END