CREATE PROCEDURE PRATTENDANCELIST
(	
	@ATTENDANCEID	INT	=	NULL
)
AS
BEGIN
	SELECT 
	     FLDATTENDANCEID
		,FLDDATE
		,FLDSLOTID
		,FLDBOOKINGID
		,FLDUSERPROFILEID
		,FLDCHILDID
		,FLDINTIME
		,FLDOUTTIME
	FROM TBLATTENDANCE
	WHERE (@ATTENDANCEID IS NULL OR FLDATTENDANCEID = @ATTENDANCEID)
END