CREATE PROCEDURE PRATTENDANCEUPDATE
(	
	  @ATTENDANCEID		INT
	 ,@DATE				DATE
	 ,@SLOTID			INT
	 ,@BOOKINGID		INT
	 ,@USERPROFILEID	INT
	 ,@CHILDID			INT
	 ,@INTIME			DATETIME
	 ,@OUTTIME			DATETIME
	 ,@USERCODE			INT
)
AS
BEGIN
	UPDATE TBLATTENDANCE
	SET 
		 FLDDATE			= @DATE
		,FLDSLOTID			= @SLOTID
		,FLDBOOKINGID		= @BOOKINGID
		,FLDUSERPROFILEID	= @USERPROFILEID
		,FLDCHILDID			= @CHILDID
		,FLDINTIME			= @INTIME
		,FLDOUTTIME			= @OUTTIME
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDATTENDANCEID	= @ATTENDANCEID
END