CREATE PROCEDURE PRATTENDANCEINSERT  
(		
	  @DATE				DATE
	 ,@SLOTID			INT
	 ,@BOOKINGID		INT
	 ,@USERPROFILEID	INT
	 ,@CHILDID			INT
	 ,@INTIME			DATETIME
	 ,@OUTTIME			DATETIME
	 ,@USERCODE			INT
)
AS
BEGIN
	DECLARE @ATTENDANCEID INT

	SELECT @ATTENDANCEID = MAX(FLDATTENDANCEID)
	FROM TBLATTENDANCE

	INSERT INTO TBLATTENDANCE
	(
		 FLDATTENDANCEID
		,FLDDATE
		,FLDSLOTID
		,FLDBOOKINGID
		,FLDUSERPROFILEID
		,FLDCHILDID
		,FLDINTIME
		,FLDOUTTIME
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@ATTENDANCEID,0) + 1
		,@DATE
		,@SLOTID
		,@BOOKINGID
		,@USERPROFILEID
		,@CHILDID
		,@INTIME
		,@OUTTIME
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END