CREATE PROCEDURE PRBRANCHINSERT  
(		
	  @BRANCHNAME				VARCHAR(100)
	 ,@ADDRESSLINE1				VARCHAR(100)
	 ,@ADDRESSLINE2				VARCHAR(100)
	 ,@ADDRESSLINE3				VARCHAR(100)
	 ,@COUNTRY					VARCHAR(50)
	 ,@STATE					VARCHAR(50)
	 ,@CITY						VARCHAR(50)
	 ,@BRANCHPH					VARCHAR(20)
	 ,@MOBILEPH					VARCHAR(20)
	 ,@CONTACTPERSON			VARCHAR(100)
	 ,@LONGITUDE				VARCHAR(50)
	 ,@LATITUDE					VARCHAR(50)
	 ,@USERCODE					INT
)
AS
BEGIN
	DECLARE @BRANCHID INT

	SELECT @BRANCHID = MAX(FLDBRANCHID)
	FROM TBLBRANCH

	INSERT INTO TBLBRANCH
	(
		  FLDBRANCHID
		, FLDBRANCHNAME
		, FLDADDRESSLINE1
		, FLDADDRESSLINE2
		, FLDADDRESSLINE3
		, FLDCOUNTRY
		, FLDSTATE
		, FLDCITY
		, FLDBRANCHPH
		, FLDMOBILEPH
		, FLDCONTACTPERSON
		, FLDLONGITUDE
		, FLDLATITUDE
		, FLDCREATEDDATE
		, FLDCREATEDBY
		, FLDMODIFIEDDATE
		, FLDMODIFIEDBY
	)
	SELECT ISNULL(@BRANCHID,0) + 1
		,@BRANCHNAME
		,@ADDRESSLINE1
		,@ADDRESSLINE2
		,@ADDRESSLINE3
		,@COUNTRY
		,@STATE
		,@CITY
		,@BRANCHPH
		,@MOBILEPH
		,@CONTACTPERSON
		,@LONGITUDE
		,@LATITUDE
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END