CREATE PROCEDURE PRBRANCHLIST
(	
	@BRANCHID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		 FLDBRANCHID
		,FLDBRANCHNAME
		,FLDADDRESSLINE1
		,FLDADDRESSLINE2
		,FLDADDRESSLINE3
		,FLDCOUNTRY
		,FLDSTATE
		,FLDCITY
		,FLDBRANCHPH
		,FLDMOBILEPH
		,FLDCONTACTPERSON
		,FLDLONGITUDE
		,FLDLATITUDE
	FROM TBLBRANCH
	WHERE (@BRANCHID IS NULL OR FLDBRANCHID = @BRANCHID)
END