CREATE PROCEDURE PRCHILDPICKUPPERSONLIST
(	
	@CHILDPICKUPPERSONID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		 FLDCHILDPICKUPPERSONID
		,FLDCHILDID
		,FLDUSERID
		,FLDUSERPROFILEID
		,FLDPERSONNAME
		,FLDPHONE
		,FLDPHOTOPATH
		,FLDSAMEASPARENTYN
	FROM TBLCHILDPICKUPPERSON
	WHERE (@CHILDPICKUPPERSONID IS NULL OR FLDCHILDPICKUPPERSONID = @CHILDPICKUPPERSONID)
END