CREATE PROCEDURE PRCHILDLIST
(	
	@CHILDID	INT	=	NULL
)
AS
BEGIN
	SELECT FLDCHILDID
			,FLDUSERID
			,FLDUSERPROFILEID
			,FLDFIRSTNAME
			,FLDMIDDLENAME
			,FLDLASTNAME
			,FLDDOB
			,FLDGENDER
			,FLDPHOTOPATH
	FROM TBLCHILD
	WHERE (@CHILDID IS NULL OR FLDCHILDID = @CHILDID)
END