CREATE PROCEDURE PRCHILDPICKUPPERSONINSERT  
(		
	 @CHILDID			INT 
	,@USERID			INT
	,@USERPROFILEID		INT
	,@PERSONNAME		VARCHAR(100)
	,@PHONE				VARCHAR(20)
	,@PHOTOPATH			NVARCHAR(MAX)
	,@SAMEASPARENTYN	TINYINT
	,@USERCODE			INT
)
AS
BEGIN
	DECLARE @CHILDPICKUPPERSONID INT

	SELECT @CHILDPICKUPPERSONID = MAX(FLDCHILDPICKUPPERSONID)
	FROM TBLCHILDPICKUPPERSON

	INSERT INTO TBLCHILDPICKUPPERSON
	(
		 FLDCHILDPICKUPPERSONID
		,FLDCHILDID
		,FLDUSERID
		,FLDUSERPROFILEID
		,FLDPERSONNAME
		,FLDPHONE
		,FLDPHOTOPATH
		,FLDSAMEASPARENTYN
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY	
	)
	SELECT ISNULL(@CHILDPICKUPPERSONID,0) + 1
		,@CHILDID
		,@USERID
		,@USERPROFILEID
		,@PERSONNAME
		,@PHONE
		,@PHOTOPATH
		,@SAMEASPARENTYN		
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END