CREATE PROCEDURE PRCHILDPICKUPPERSONDELETE
(	
	 @CHILDPICKUPPERSONID			INT	
	,@USERCODE						INT	=	NULL
)
AS
BEGIN
	DELETE FROM TBLCHILDPICKUPPERSON
	WHERE FLDCHILDPICKUPPERSONID = @CHILDPICKUPPERSONID
END