CREATE PROCEDURE PRCHILDUPDATE
(	
	@CHILDID			INT
	,@USERID			INT			
	,@USERPROFILEID		INT			
	,@FIRSTNAME			VARCHAR(100)
	,@MIDDLENAME		VARCHAR(100)
	,@LASTNAME			VARCHAR(100)
	,@DOB				DATE
	,@GENDER			VARCHAR(100)
	,@PHOTOPATH			NVARCHAR(MAX)
	,@USERCODE			INT
)
AS
BEGIN
	UPDATE TBLCHILD
	SET FLDUSERID			= @USERID			
		,FLDUSERPROFILEID	= @USERPROFILEID		
		,FLDFIRSTNAME		= @FIRSTNAME			
		,FLDMIDDLENAME		= @MIDDLENAME		
		,FLDLASTNAME		= @LASTNAME			
		,FLDDOB				= @DOB				
		,FLDGENDER			= @GENDER			
		,FLDPHOTOPATH		= @PHOTOPATH			
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDCHILDID		= @CHILDID
END