CREATE PROCEDURE PRCHILDPICKUPPERSONUPDATE
(	
	 @CHILDPICKUPPERSONID			INT
	,@CHILDID						INT
	,@USERID						INT
	,@USERPROFILEID					INT
	,@PERSONNAME					VARCHAR(100)
	,@PHONE							VARCHAR(20)
	,@PHOTOPATH						NVARCHAR(MAX)
	,@SAMEASPARENTYN				TINYINT	
	,@USERCODE						INT
)
AS
BEGIN
	UPDATE TBLCHILDPICKUPPERSON
	SET 
		 FLDCHILDID			= @CHILDID
		,FLDUSERID			= @USERID
		,FLDUSERPROFILEID	= @USERPROFILEID
		,FLDPERSONNAME		= @PERSONNAME
		,FLDPHONE			= @PHONE
		,FLDPHOTOPATH		= @PHOTOPATH
		,FLDSAMEASPARENTYN	= @SAMEASPARENTYN
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDCHILDPICKUPPERSONID = @CHILDPICKUPPERSONID
END