CREATE PROCEDURE PRCHILDINSERT  
(		
	@USERID				INT			
	,@USERPROFILEID		INT			
	,@FIRSTNAME			VARCHAR(100)
	,@MIDDLENAME		VARCHAR(100)
	,@LASTNAME			VARCHAR(100)
	,@DOB				DATE
	,@GENDER			VARCHAR(100)
	,@PHOTOPATH			NVARCHAR(MAX)
	,@USERCODE			INT
)
AS
BEGIN
	DECLARE @CHILDID INT

	SELECT @CHILDID = MAX(FLDCHILDID)
	FROM TBLCHILD

	INSERT INTO TBLCHILD
	(
		FLDCHILDID			
		,FLDUSERID			
		,FLDUSERPROFILEID	
		,FLDFIRSTNAME		
		,FLDMIDDLENAME		
		,FLDLASTNAME		
		,FLDDOB				
		,FLDGENDER			
		,FLDPHOTOPATH		
		,FLDCREATEDDATE		
		,FLDCREATEDBY		
		,FLDMODIFIEDDATE	
		,FLDMODIFIEDBY			
	)
	SELECT ISNULL(@CHILDID,0) + 1
		,@USERID				
		,@USERPROFILEID		
		,@FIRSTNAME			
		,@MIDDLENAME		
		,@LASTNAME			
		,@DOB				
		,@GENDER			
		,@PHOTOPATH				
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END