CREATE PROCEDURE PRORGANISATIONUPDATE
(	
	  @ORGANISATIONID			INT
	, @ORGNAME					VARCHAR(100)
	, @ORGREGNUMBER				VARCHAR(100)
	, @ADDRESSLINE1				VARCHAR(100)
	, @ADDRESSLINE2				VARCHAR(100)
	, @ADDRESSLINE3				VARCHAR(100)
	, @COUNTRY					VARCHAR(50)
	, @STATE					VARCHAR(50)
	, @CITY						VARCHAR(50)
	, @OFFICEPH					VARCHAR(20)
	, @MOBILEPH					VARCHAR(20)
	, @LONGITUDE				VARCHAR(50)
	, @LATITUDE					VARCHAR(50)
	, @BASECURRENCY				VARCHAR(4)
	, @USERCODE						INT
)
AS
BEGIN
	UPDATE TBLORGANISATION
	SET 
		 
		FLDORGNAME				= @ORGNAME
		,FLDORGREGNUMBER		= @ORGREGNUMBER
		,FLDADDRESSLINE1		= @ADDRESSLINE1
		,FLDADDRESSLINE2		= @ADDRESSLINE2
		,FLDADDRESSLINE3		= @ADDRESSLINE3
		,FLDCOUNTRY				= @COUNTRY	
		,FLDSTATE				= @STATE
		,FLDCITY				= @CITY
		,FLDOFFICEPH			= @OFFICEPH
		,FLDMOBILEPH			= @MOBILEPH	
		,FLDLONGITUDE			= @LONGITUDE	
		,FLDLATITUDE			= @LATITUDE	
		,FLDBASECURRENCY		= @BASECURRENCY
		,FLDMODIFIEDDATE		= GETUTCDATE()
		,FLDMODIFIEDBY			= @USERCODE
	WHERE FLDORGANISATIONID = @ORGANISATIONID
END