CREATE PROCEDURE PRPAYMENTINSERT  
(		
	 @BOOKINGID				INT
	,@USERID				INT
	,@USERPROFILEID			INT
	,@TRANSACTIONREFNO		VARCHAR(50)
	,@DATE					DATE
	,@AMOUNT				DECIMAL(10,2)
	,@STATUS				VARCHAR(10)
	,@APIRESPONSEMESSAGE	NVARCHAR(MAX)
	,@USERCODE				INT
)
AS
BEGIN
	DECLARE @PAYMENTID INT

	SELECT @PAYMENTID = MAX(FLDPAYMENTID)
	FROM TBLPAYMENT

	INSERT INTO TBLPAYMENT
	(
		 FLDPAYMENTID
		,FLDBOOKINGID
		,FLDUSERID
		,FLDUSERPROFILEID
		,FLDTRANSACTIONREFNO
		,FLDDATE
		,FLDAMOUNT
		,FLDSTATUS
		,FLDAPIRESPONSEMESSAGE
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@PAYMENTID,0) + 1
		,@BOOKINGID
		,@USERID
		,@USERPROFILEID
		,@TRANSACTIONREFNO
		,@DATE
		,@AMOUNT
		,@STATUS
		,@APIRESPONSEMESSAGE
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END