CREATE PROCEDURE PRPAYMENTUPDATE
(	
	 @PAYMENTID				INT
	,@BOOKINGID				INT
	,@USERID				INT
	,@USERPROFILEID			INT
	,@TRANSACTIONREFNO		VARCHAR(50)
	,@DATE					DATE
	,@AMOUNT				DECIMAL(10,2)
	,@STATUS				VARCHAR(10)
	,@APIRESPONSEMESSAGE	NVARCHAR(MAX)
	,@USERCODE				INT
)
AS
BEGIN
	UPDATE TBLPAYMENT
	SET 
		 FLDBOOKINGID			= @BOOKINGID
		,FLDUSERID				= @USERID
		,FLDUSERPROFILEID		= @USERPROFILEID
		,FLDTRANSACTIONREFNO	= @TRANSACTIONREFNO
		,FLDDATE				= @DATE
		,FLDAMOUNT				= @AMOUNT
		,FLDSTATUS				= @STATUS
		,FLDAPIRESPONSEMESSAGE	= @APIRESPONSEMESSAGE
		,FLDMODIFIEDDATE		= GETUTCDATE()
		,FLDMODIFIEDBY			= @USERCODE
	WHERE FLDPAYMENTID = @PAYMENTID
END