CREATE PROCEDURE PRPAYMENTLIST
(	
	@PAYMENTID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		 FLDPAYMENTID
		,FLDBOOKINGID
		,FLDUSERID
		,FLDUSERPROFILEID
		,FLDTRANSACTIONREFNO
		,FLDDATE
		,FLDAMOUNT
		,FLDSTATUS
		,FLDAPIRESPONSEMESSAGE
	FROM TBLPAYMENT
	WHERE (@PAYMENTID IS NULL OR FLDPAYMENTID = @PAYMENTID)
END