CREATE PROCEDURE PRPLANSINSERT  
(		
	 @PLANNAME						VARCHAR(100)
	,@TIMECHANGEYN					TINYINT
	,@DAYWEEKCHANGEYN				TINYINT
	,@DURATIONFLEXIBILITYYN			TINYINT
	,@CANCELLATIONYN				TINYINT
	,@WAITLISTYN					TINYINT
	,@GUESTSYN						TINYINT
	,@FOODYN						TINYINT
	,@LATEFEEYN						TINYINT
	,@LATEFEEBILLCYCLE				INT
	,@ENTRYOUTYN					TINYINT
	,@REFERALBENEFITYN				TINYINT
	,@SCHEDULECOMMUNICATIONYN		TINYINT
	,@GALLERYYN						TINYINT
	,@NOTIFICATIONSYN				TINYINT
	,@CIRCULARYN					TINYINT
	,@SIBLINGYN						TINYINT
	,@PAYMENTYN						TINYINT
	,@TOTALHOURS					INT
	,@MAXHOURSINADAY				INT
	,@MAXDAYSFROMREGISTRATION		INT
	,@USERCODE						INT
)
AS
BEGIN
	DECLARE @PLANID INT

	SELECT @PLANID = MAX(FLDPLANID)
	FROM TBLPLANS

	INSERT INTO TBLPLANS
	(
		 FLDPLANID
		,FLDPLANNAME
		,FLDTIMECHANGEYN
		,FLDDAYWEEKCHANGEYN
		,FLDDURATIONFLEXIBILITYYN
		,FLDCANCELLATIONYN
		,FLDWAITLISTYN
		,FLDGUESTSYN
		,FLDFOODYN
		,FLDLATEFEEYN
		,FLDLATEFEEBILLCYCLE
		,FLDENTRYOUTYN
		,FLDREFERALBENEFITYN
		,FLDSCHEDULECOMMUNICATIONYN
		,FLDGALLERYYN
		,FLDNOTIFICATIONSYN
		,FLDCIRCULARYN
		,FLDSIBLINGYN
		,FLDPAYMENTYN
		,FLDTOTALHOURS
		,FLDMAXHOURSINADAY
		,FLDMAXDAYSFROMREGISTRATION
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@PLANID,0) + 1
		,@PLANNAME
		,@TIMECHANGEYN
		,@DAYWEEKCHANGEYN
		,@DURATIONFLEXIBILITYYN
		,@CANCELLATIONYN
		,@WAITLISTYN
		,@GUESTSYN
		,@FOODYN
		,@LATEFEEYN
		,@LATEFEEBILLCYCLE
		,@ENTRYOUTYN
		,@REFERALBENEFITYN
		,@SCHEDULECOMMUNICATIONYN
		,@GALLERYYN
		,@NOTIFICATIONSYN
		,@CIRCULARYN
		,@SIBLINGYN
		,@PAYMENTYN
		,@TOTALHOURS
		,@MAXHOURSINADAY
		,@MAXDAYSFROMREGISTRATION
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END