CREATE PROCEDURE PRPLANSUPDATE
(	
	 @PLANID						INT
	,@PLANNAME						VARCHAR(100)
	,@TIMECHANGEYN					TINYINT
	,@DAYWEEKCHANGEYN				TINYINT
	,@DURATIONFLEXIBILITYYN			TINYINT
	,@CANCELLATIONYN				TINYINT
	,@WAITLISTYN					TINYINT
	,@GUESTSYN						TINYINT
	,@FOODYN						TINYINT
	,@LATEFEEYN						TINYINT
	,@LATEFEEBILLCYCLE				INT
	,@ENTRYOUTYN					TINYINT
	,@REFERALBENEFITYN				TINYINT
	,@SCHEDULECOMMUNICATIONYN		TINYINT
	,@GALLERYYN						TINYINT
	,@NOTIFICATIONSYN				TINYINT
	,@CIRCULARYN					TINYINT
	,@SIBLINGYN						TINYINT
	,@PAYMENTYN						TINYINT
	,@TOTALHOURS					INT
	,@MAXHOURSINADAY				INT
	,@MAXDAYSFROMREGISTRATION		INT
	,@USERCODE						INT
)
AS
BEGIN
	UPDATE TBLPLANS
	SET 
		 FLDPLANNAME					= @PLANNAME
		,FLDTIMECHANGEYN				= @TIMECHANGEYN
		,FLDDAYWEEKCHANGEYN				= @DAYWEEKCHANGEYN
		,FLDDURATIONFLEXIBILITYYN		= @DURATIONFLEXIBILITYYN
		,FLDCANCELLATIONYN				= @CANCELLATIONYN
		,FLDWAITLISTYN					= @WAITLISTYN
		,FLDGUESTSYN					= @GUESTSYN
		,FLDFOODYN						= @FOODYN
		,FLDLATEFEEYN					= @LATEFEEYN
		,FLDLATEFEEBILLCYCLE			= @LATEFEEBILLCYCLE
		,FLDENTRYOUTYN					= @ENTRYOUTYN
		,FLDREFERALBENEFITYN			= @REFERALBENEFITYN
		,FLDSCHEDULECOMMUNICATIONYN		= @SCHEDULECOMMUNICATIONYN
		,FLDGALLERYYN					= @GALLERYYN
		,FLDNOTIFICATIONSYN				= @NOTIFICATIONSYN
		,FLDCIRCULARYN					= @CIRCULARYN
		,FLDSIBLINGYN					= @SIBLINGYN
		,FLDPAYMENTYN					= @PAYMENTYN
		,FLDTOTALHOURS					= @TOTALHOURS
		,FLDMAXHOURSINADAY				= @MAXHOURSINADAY
		,FLDMAXDAYSFROMREGISTRATION		= @MAXDAYSFROMREGISTRATION
		,FLDMODIFIEDDATE				= GETUTCDATE()
		,FLDMODIFIEDBY					= @USERCODE
	WHERE FLDPLANID = @PLANID
END