CREATE PROCEDURE PRSLOTBRANCHMAPINSERT  
(	
	 @BRANCHID			INT
	,@SLOTID			INT
	,@MAXCHILD			INT
	,@USERCODE			INT
)
AS
BEGIN
	DECLARE @SLOTMAPID INT

	SELECT @SLOTMAPID = MAX(FLDSLOTMAPID)
	FROM TBLSLOTBRANCHMAP

	INSERT INTO TBLSLOTBRANCHMAP
	(
		 FLDSLOTMAPID
		,FLDBRANCHID
		,FLDSLOTID
		,FLDMAXCHILD
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@SLOTMAPID,0) + 1
		,@BRANCHID
		,@SLOTID
		,@MAXCHILD		
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END