CREATE PROCEDURE PRSLOTSUPDATE
(	
	 @SLOTID			INT
	,@SLOTNAME			VARCHAR(100)	
	,@STARTTIME			TIME
	,@ENDTIME			TIME
	,@USERCODE			INT
)
AS
BEGIN
	UPDATE TBLSLOTS
	SET 
		  FLDSLOTNAME		= @SLOTNAME	
		 ,FLDSTARTTIME		= @STARTTIME	
		 ,FLDENDTIME		= @ENDTIME	
		 ,FLDMODIFIEDDATE	= GETUTCDATE()
		 ,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDSLOTID = @SLOTID
END