CREATE PROCEDURE PRSLOTBOOKINGINSERT  
(		
	 @BOOKINGID				INT
	,@USERID				INT
	,@USERPROFILEID			INT
	,@CHILDID				INT
	,@BRANCHID				INT
	,@SLOTID				INT
	,@DATE					DATE
	,@STATUS				VARCHAR(10)
	,@BOOKINGNUMBER			VARCHAR(10)
	,@USERCODE				INT
)
AS
BEGIN
	DECLARE @SLOTBOOKINGID INT

	SELECT @SLOTBOOKINGID = MAX(FLDSLOTBOOKINGID)
	FROM TBLSLOTBOOKING

	INSERT INTO TBLSLOTBOOKING
	(
		 FLDSLOTBOOKINGID
		,FLDBOOKINGID
		,FLDUSERID
		,FLDUSERPROFILEID
		,FLDCHILDID
		,FLDBRANCHID
		,FLDSLOTID
		,FLDDATE
		,FLDSTATUS
		,FLDBOOKINGNUMBER
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@SLOTBOOKINGID,0) + 1
		,@BOOKINGID
		,@USERID
		,@USERPROFILEID
		,@CHILDID
		,@BRANCHID
		,@SLOTID
		,@DATE
		,@STATUS
		,@BOOKINGNUMBER
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END