CREATE PROCEDURE PRSLOTSINSERT  
(		
	 @SLOTNAME			VARCHAR(100)	
	,@STARTTIME			TIME
	,@ENDTIME			TIME
	,@USERCODE			INT
)
AS
BEGIN
	DECLARE @SLOTID INT

	SELECT @SLOTID = MAX(FLDSLOTID)
	FROM TBLSLOTS

	INSERT INTO TBLSLOTS
	(
		 FLDSLOTID
		,FLDSLOTNAME
		,FLDSTARTTIME
		,FLDENDTIME
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@SLOTID,0) + 1
		,@SLOTNAME
		,@STARTTIME
		,@ENDTIME		
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END