CREATE PROCEDURE PRSLOTBRANCHMAPUPDATE
(	
	 @SLOTMAPID			INT
	,@BRANCHID			INT
	,@SLOTID			INT
	,@MAXCHILD			INT
	,@USERCODE			INT
)
AS
BEGIN
	UPDATE TBLSLOTBRANCHMAP
	SET 
		 FLDBRANCHID		= @BRANCHID		
		,FLDSLOTID			= @SLOTID
		,FLDMAXCHILD		= @MAXCHILD
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDSLOTMAPID		= @SLOTMAPID
END