CREATE PROCEDURE PRSLOBBOOKINGSUMMARYDELETE
(	
	 @SLOBBOOKINGSUMMARYID			INT	
	,@USERCODE						INT	=	NULL
)
AS
BEGIN
	DELETE FROM TBLSLOBBOOKINGSUMMARY
	WHERE FLDSLOBBOOKINGSUMMARYID = @SLOBBOOKINGSUMMARYID
END