CREATE PROCEDURE PRSLOTBRANCHMAPLIST
(	
	@SLOTMAPID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		FLDSLOTMAPID
		,FLDBRANCHID
		,FLDSLOTID
		,FLDMAXCHILD
	FROM TBLSLOTBRANCHMAP
	WHERE (@SLOTMAPID IS NULL OR FLDSLOTMAPID = @SLOTMAPID)
END