CREATE PROCEDURE PRSLOBBOOKINGSUMMARYINSERT  
(		
	 @BRANCHID					INT
	,@DATE						DATE
	,@SLOTID					INT
	,@BOOKINGCOUNT				INT
	,@AVAILABLECOUNT			INT
	,@USERCODE					INT
)
AS
BEGIN
	DECLARE @SLOBBOOKINGSUMMARYID INT

	SELECT @SLOBBOOKINGSUMMARYID = MAX(FLDSLOBBOOKINGSUMMARYID)
	FROM TBLSLOBBOOKINGSUMMARY

	INSERT INTO TBLSLOBBOOKINGSUMMARY
	(
		 FLDSLOBBOOKINGSUMMARYID
		,FLDBRANCHID
		,FLDDATE
		,FLDSLOTID
		,FLDBOOKINGCOUNT
		,FLDAVAILABLECOUNT
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@SLOBBOOKINGSUMMARYID,0) + 1
		,@BRANCHID
		,@DATE
		,@SLOTID
		,@BOOKINGCOUNT
		,@AVAILABLECOUNT
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END