CREATE PROCEDURE PRSLOTBOOKINGUPDATE
(	
	 @SLOTBOOKINGID			INT
	,@BOOKINGID				INT
	,@USERID				INT
	,@USERPROFILEID			INT
	,@CHILDID				INT
	,@BRANCHID				INT
	,@SLOTID				INT
	,@DATE					DATE
	,@STATUS				VARCHAR(10)
	,@BOOKINGNUMBER			VARCHAR(10)
	,@USERCODE				INT
)
AS
BEGIN
	UPDATE TBLSLOTBOOKING
	SET 
		 FLDBOOKINGID		= @BOOKINGID
		,FLDUSERID			= @USERID
		,FLDUSERPROFILEID	= @USERPROFILEID
		,FLDCHILDID			= @CHILDID
		,FLDBRANCHID		= @BRANCHID
		,FLDSLOTID			= @SLOTID
		,FLDDATE			= @DATE
		,FLDSTATUS			= @STATUS
		,FLDBOOKINGNUMBER	= @BOOKINGNUMBER
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDSLOTBOOKINGID = @SLOTBOOKINGID
END