CREATE PROCEDURE PRSLOTBOOKINGLIST
(	
	@SLOTBOOKINGID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		  FLDSLOTBOOKINGID
		 ,FLDBOOKINGID
		 ,FLDUSERID
		 ,FLDUSERPROFILEID
		 ,FLDCHILDID
		 ,FLDBRANCHID
		 ,FLDSLOTID
		 ,FLDDATE
		 ,FLDSTATUS
		 ,FLDBOOKINGNUMBER
	FROM TBLSLOTBOOKING
	WHERE (@SLOTBOOKINGID IS NULL OR FLDSLOTBOOKINGID = @SLOTBOOKINGID)
END