CREATE PROCEDURE PRSLOBBOOKINGSUMMARYUPDATE
(	
	 @SLOBBOOKINGSUMMARYID		INT
	,@BRANCHID					INT
	,@DATE						DATE
	,@SLOTID					INT
	,@BOOKINGCOUNT				INT
	,@AVAILABLECOUNT			INT
	,@USERCODE					INT
)
AS
BEGIN
	UPDATE TBLSLOBBOOKINGSUMMARY
	SET 
		 FLDBRANCHID		= @BRANCHID
		,FLDDATE			= @DATE
		,FLDSLOTID			= @SLOTID
		,FLDBOOKINGCOUNT	= @BOOKINGCOUNT
		,FLDAVAILABLECOUNT	= @AVAILABLECOUNT
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDSLOBBOOKINGSUMMARYID = @SLOBBOOKINGSUMMARYID
END