CREATE PROCEDURE PRSTAFFINSERT  
(		
	  @NAME				VARCHAR(100)
	 ,@USERNAME			VARCHAR(100)
	 ,@PASSWORD			VARCHAR(10)
	 ,@CONTACTNO		VARCHAR(10)
	 ,@EMAILID			VARCHAR(50)
	 ,@GENDER			VARCHAR(10)
	 ,@DOJ				DATE
	 ,@ROLE				VARCHAR(50)
	 ,@USERCODE			INT
)
AS
BEGIN
	DECLARE @STAFFID INT

	SELECT @STAFFID = MAX(FLDSTAFFID)
	FROM TBLSTAFF

	INSERT INTO TBLSTAFF
	(
		 FLDSTAFFID
		,FLDNAME
		,FLDUSERNAME
		,FLDPASSWORD
		,FLDCONTACTNO
		,FLDEMAILID
		,FLDGENDER
		,FLDDOJ
		,FLDROLE
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@STAFFID,0) + 1
		,@NAME
		,@USERNAME
		,@PASSWORD
		,@CONTACTNO
		,@EMAILID
		,@GENDER
		,@DOJ
		,@ROLE
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END