CREATE PROCEDURE PRSTAFFBRANCHLIST
(	
	@STAFFBRANCHID	INT	=	NULL
)
AS
BEGIN
	SELECT 
	     FLDSTAFFBRANCHID
		,FLDSTAFFID
		,FLDBRANCHID
	FROM TBLSTAFFBRANCH
	WHERE (@STAFFBRANCHID IS NULL OR FLDSTAFFBRANCHID = @STAFFBRANCHID)
END