CREATE PROCEDURE PRSTAFFBRANCHUPDATE
(	
	  @STAFFBRANCHID    INT
	 ,@STAFFID			INT
	 ,@BRANCHID			INT
	 ,@USERCODE			INT
)
AS
BEGIN
	UPDATE TBLSTAFFBRANCH
	SET 
		 FLDSTAFFID			= @STAFFID
		,FLDBRANCHID		= @BRANCHID
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDSTAFFBRANCHID = @STAFFBRANCHID
END