CREATE PROCEDURE PRUSERPROFILEUPDATE
(
	 @USERPROFILEID			INT			
	,@USERID				INT			
	,@FIRSTNAME				VARCHAR(100)
	,@LASTNAME				VARCHAR(100)
	,@MIDDLENAME			VARCHAR(100)
	,@DOB					DATE
	,@REGISTRATIONDATE		DATE
	,@COUNTRYCODE			INT
	,@GENDER				VARCHAR(100)
	,@QUALIFICATION			VARCHAR(100)
	,@OCCUPATION			VARCHAR(100)
	,@ANNUALINCODE			VARCHAR(100)
	,@DEFAULTPAYMENTCARD	INT			
	,@PHOTOPATH				NVARCHAR(MAX)
	,@USERCODE				INT
)
AS
BEGIN
	UPDATE TBLUSERPROFILE
	SET FLDUSERID				= @USERID				
		,FLDFIRSTNAME			= @FIRSTNAME				
		,FLDLASTNAME			= @LASTNAME				
		,FLDMIDDLENAME			= @MIDDLENAME			
		,FLDDOB					= @DOB					
		,FLDREGISTRATIONDATE	= @REGISTRATIONDATE		
		,FLDCOUNTRYCODE			= @COUNTRYCODE			
		,FLDGENDER				= @GENDER				
		,FLDQUALIFICATION		= @QUALIFICATION			
		,FLDOCCUPATION			= @OCCUPATION			
		,FLDANNUALINCODE		= @ANNUALINCODE			
		,FLDDEFAULTPAYMENTCARD	= @DEFAULTPAYMENTCARD	
		,FLDPHOTOPATH			= @PHOTOPATH				
		,FLDMODIFIEDDATE		= GETUTCDATE()
		,FLDMODIFIEDBY			= @USERCODE
	WHERE FLDUSERPROFILEID		= @USERPROFILEID
END