CREATE PROCEDURE PRUSERCREDITCARDLIST
(	
	@CARDID	INT	=	NULL
)
AS
BEGIN
	SELECT FLDCARDID
			,FLDUSERID
			,FLDUSERPROFILEID
			,FLDCARDHOLDERNAME
			,FLDCARDTYPE
			,FLDCARDNUMBER
			,FLDEXPIRYDATE
	FROM TBLUSERCREDITCARD
	WHERE (@CARDID IS NULL OR FLDCARDID = @CARDID)
END