CREATE PROCEDURE PRUSERINSERT  
(		
	@USERNAME				VARCHAR(100)
	,@EMAIL					NVARCHAR(100)
	,@PASSWORD				NVARCHAR(200)
	,@EMAILVERIFIEDYN		TINYINT
	,@MOBILENO				VARCHAR(20)
	,@MOBILENOVERIFIEDYN	TINYINT
	,@USERCODE				INT
)
AS
BEGIN
	DECLARE @USERID INT

	SELECT @USERID = MAX(FLDUSERID)
	FROM TBLUSER

	INSERT INTO TBLUSER
	(
		FLDUSERID				
		,FLDUSERNAME			
		,FLDEMAIL				
		,FLDPASSWORD			
		,FLDEMAILVERIFIEDYN		
		,FLDMOBILENO			
		,FLDMOBILENOVERIFIEDYN	
		,FLDCREATEDDATE			
		,FLDCREATEDBY			
		,FLDMODIFIEDDATE		
		,FLDMODIFIEDBY			
	)
	SELECT ISNULL(@USERID,0) + 1
		,@USERNAME				
		,@EMAIL					
		,HASHBYTES('MD5', @PASSWORD)				
		,@EMAILVERIFIEDYN		
		,@MOBILENO				
		,@MOBILENOVERIFIEDYN	
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END