CREATE PROCEDURE PRUSERUPDATE
(	
	@USERID					INT	
	,@USERNAME				VARCHAR(100)
	,@EMAIL					VARCHAR(100)
	,@PASSWORD				NVARCHAR(200)
	,@EMAILVERIFIEDYN		TINYINT
	,@MOBILENO				VARCHAR(20)
	,@MOBILENOVERIFIEDYN	TINYINT
	,@USERCODE				INT
)
AS
BEGIN
	UPDATE TBLUSER
	SET FLDUSERNAME					= @USERNAME				
		,FLDEMAIL					= @EMAIL					
		,FLDPASSWORD				= HASHBYTES('MD5', @PASSWORD)
		,FLDEMAILVERIFIEDYN			= @EMAILVERIFIEDYN		
		,FLDMOBILENO				= @MOBILENO				
		,FLDMOBILENOVERIFIEDYN		= @MOBILENOVERIFIEDYN	
		,FLDMODIFIEDDATE			= GETUTCDATE()
		,FLDMODIFIEDBY				= @USERCODE
	WHERE FLDUSERID					= @USERID
END
