CREATE PROCEDURE PRUSERPROFILEINSERT
(		
	@USERID					INT					
	,@FIRSTNAME				VARCHAR(100)
	,@LASTNAME				VARCHAR(100)
	,@MIDDLENAME			VARCHAR(100)	
	,@DOB					DATE	
	,@REGISTRATIONDATE		DATE
	,@COUNTRYCODE			INT	
	,@GENDER				VARCHAR(100)	
	,@QUALIFICATION			VARCHAR(100)
	,@OCCUPATION			VARCHAR(100)	
	,@ANNUALINCODE			VARCHAR(100)
	,@DEFAULTPAYMENTCARD	INT					
	,@PHOTOPATH				NVARCHAR(MAX)
	,@USERCODE				INT
)
AS
BEGIN
	DECLARE @USERPROFILEID INT

	SELECT @USERPROFILEID = MAX(FLDUSERPROFILEID)
	FROM TBLUSERPROFILE

	INSERT INTO TBLUSERPROFILE
	(
		 FLDUSERPROFILEID		
		,FLDUSERID				
		,FLDFIRSTNAME			
		,FLDLASTNAME			
		,FLDMIDDLENAME			
		,FLDDOB					
		,FLDREGISTRATIONDATE	
		,FLDCOUNTRYCODE			
		,FLDGENDER				
		,FLDQUALIFICATION		
		,FLDOCCUPATION			
		,FLDANNUALINCODE		
		,FLDDEFAULTPAYMENTCARD	
		,FLDPHOTOPATH			
		,FLDCREATEDDATE			
		,FLDCREATEDBY			
		,FLDMODIFIEDDATE		
		,FLDMODIFIEDBY			
	)
	VALUES
	(	
		ISNULL(@USERPROFILEID,0) + 1
		,@USERID				
		,@FIRSTNAME				
		,@LASTNAME				
		,@MIDDLENAME			
		,@DOB					
		,@REGISTRATIONDATE		
		,@COUNTRYCODE			
		,@GENDER				
		,@QUALIFICATION			
		,@OCCUPATION			
		,@ANNUALINCODE			
		,@DEFAULTPAYMENTCARD	
		,@PHOTOPATH			
		,GETUTCDATE()
		,@USERCODE			
		,GETUTCDATE()
		,@USERCODE	
	)
END


















