CREATE PROCEDURE PRUSERLIST
(	
	@USERID	INT	=	NULL
)
AS
BEGIN
	SELECT FLDUSERID				
		,FLDUSERNAME			
		,FLDEMAIL				
		,CONVERT(VARCHAR(200),FLDPASSWORD) AS FLDPASSWORD
		,FLDEMAILVERIFIEDYN		
		,FLDMOBILENO			
		,FLDMOBILENOVERIFIEDYN	
	FROM TBLUSER
	WHERE (@USERID IS NULL OR FLDUSERID = @USERID)
END