CREATE PROCEDURE PRUSERCREDITCARDINSERT  
(		
	@USERID				INT			
	,@USERPROFILEID		INT			
	,@CARDHOLDERNAME	VARCHAR(100)
	,@CARDTYPE			VARCHAR(10)
	,@CARDNUMBER		VARCHAR(50)
	,@EXPIRYDATE		DATE
	,@USERCODE			INT
)
AS
BEGIN
	DECLARE @USERCREDITCARDID INT

	SELECT @USERCREDITCARDID = MAX(FLDCARDID)
	FROM TBLUSERCREDITCARD

	INSERT INTO TBLUSERCREDITCARD
	(
		FLDCARDID
		,FLDUSERID
		,FLDUSERPROFILEID
		,FLDCARDHOLDERNAME
		,FLDCARDTYPE
		,FLDCARDNUMBER
		,FLDEXPIRYDATE
		,FLDCREATEDDATE
		,FLDCREATEDBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY	
	)
	SELECT ISNULL(@USERCREDITCARDID,0) + 1
		,@USERID				
		,@USERPROFILEID		
		,@CARDHOLDERNAME	
		,@CARDTYPE			
		,@CARDNUMBER		
		,@EXPIRYDATE					
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END